
/* VALIDAR */
select max(matr_id) from FORACESSO.MATRICULADO --23
select max(pess_id) from FORACESSO.PESSOA --37
select * from FORACESSO.SEQUENCIAL
where SEQUELEMENTO in (23,37)

/* CORRIGIR */
UPDATE FORACESSO.SEQUENCIAL
SET SEQUVALOR =
CASE WHEN SEQUELEMENTO = 23 THEN 
	(select max(matr_id) from FORACESSO.MATRICULADO)
WHEN SEQUELEMENTO = 37 THEN 
	(select max(pess_id) from FORACESSO.PESSOA) END
where SEQUELEMENTO in (23,37)